[package]
name = "alpha_scout"
version = "0.1.0"
description = "On-chain AI Trend Score Ledger"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "alpha_scout"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
